sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t leolins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leolins/docker-react npm run test
